name: ml

services:

    # Influxdb server
    influxdb:
        build: ./influx
        container_name: influxdb
        restart: unless-stopped
        networks:
            - database
        ports:
            - "8086:8086"
        volumes:
            - ./influx/database:/var/lib/influxdb2
        healthcheck:
            test: ["CMD", "influx", "ping"]
            interval: 5s
            timeout: 30s
            retries: 10

    # MySQL
    mysql:
        build: ./mysql
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: username
            MYSQL_PASSWORD: password
        networks:
            - database
        ports:
            - 3307:3306
        expose:
            - 3307
        volumes:
            - ./mysql/database:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
            interval: 5s
            timeout: 30s
            retries: 10

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        networks:
            - database
        ports:
            - 8080:80
        links:
            - mysql:db

    # Socket
    socket:
        build: ./socket
        container_name: socket
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
            influxdb:
                condition: service_healthy
        networks:
            - database
        ports:
            - 3300:3300
        expose:
            - 3300

networks:
    database:
