services:

    # Influxdb server
    influxdb:
        build: .
        container_name: influxdb
        restart: unless-stopped
        networks:
        - database
        ports:
          - "8086:8086"
        volumes:
          - ./influxdb:/var/lib/influxdb2

        # command: ./setup.sh

        # healthcheck:
        #     test: "influx ping"
        #     interval: 2s
        #     retries: 5

    # # Setup Influxdb
    # influx-cli:
    #     image: influxdb:latest
    #     container_name: influxdb-cli
    #     restart: on-failure:10
    #     networks:
    #     - database
    #     depends_on:
    #         influxdb:
    #             condition: service_healthy
    #     entrypoint: >
    #         influx setup
    #         --bucket metrics
    #         --org ml
    #         --username=username
    #         --password=password
    #         --token=token
    #         --host=http://influxdb:8086
    #         --force
    #

    # nginx:
    #     whater

networks:
    database:
