name: ml

services:

    # # Influxdb server
    # influxdb:
    #     build: ./influx
    #     container_name: influxdb
    #     restart: unless-stopped
    #     networks:
    #         - database
    #     ports:
    #         - "8086:8086"
    #     volumes:
    #         - ./influx/database:/var/lib/influxdb2

    # MySQL
    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "metrics"
        networks:
            - database
        ports:
            - "3307:3306"
        volumes:
            - ./mysql/database:/var/lib/mysql


networks:
    database:
