name: ml

services:

    # Influxdb (Backend + Frontend)
    influxdb:
        build: ./influx
        container_name: influxdb
        restart: unless-stopped
        networks:
            - database
        ports:
            - "8086:8086"
        volumes:
            - ./influx/database:/var/lib/influxdb2
        healthcheck:
            test: ["CMD", "influx", "ping"]
            interval: 5s
            timeout: 30s
            retries: 10

    # Mongo (Backend)
    mongo:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        networks:
            - database
        ports:
            - 27017:27017
        volumes:
            - ./mongo/database:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password

    # # Mongo (Frontend)
    # mongo-express:
    #     image: mongo-express
    #     container_name: mongo-express
    #     restart: always
    #     networks:
    #         - database
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: username
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: password
    #         ME_CONFIG_MONGODB_URL: mongodb://username:password@mongo:27017/

    # # Socket
    # socket:
    #     build: ./socket
    #     container_name: socket
    #     restart: unless-stopped
    #     depends_on:
    #         influxdb:
    #             condition: service_healthy
    #     networks:
    #         - database
    #     ports:
    #         - 3300:3300
    #     expose:
    #         - 3300

networks:
    database:
